name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

    steps:
      - name: Set IS_MAIN_BRANCH if on main branch
        if: github.ref_name == 'main'
        run: echo "IS_MAIN_BRANCH=true" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get JRE 8
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          path: app_pojav_zh/src/main/assets/components/jre-8
          workflow_conclusion: success
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre8
          name: jre8-pojav

      - name: Get JRE 17
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          path: app_pojav_zh/src/main/assets/components/jre-17
          workflow_conclusion: success
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre17-21
          name: jre17-pojav

      - name: Get JRE 21
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          path: app_pojav_zh/src/main/assets/components/jre-21
          workflow_conclusion: success
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre17-21
          name: jre21-pojav

      - name: Get LWJGL3
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: main.yml
          path: app_pojav_zh/src/main/assets/components/lwjgl3
          workflow_conclusion: success
          repo: Vera-Firefly/lwjgl3-build
          branch: main
          name: lwjgl

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Release.apk
        if: github.repository_owner == 'Vera-Firefly' && github.ref_name == 'main'
        run: |
          gradle :app_pojav_zh:assemblerelease

      - name: Build Debug.apk
        run: |
          # Build the launcher
          gradle :app_pojav_zh:assembleDebug

      - name: Upload Release
        continue-on-error: true
        if: github.repository_owner == 'Vera-Firefly' && github.ref_name == 'main'
        uses: actions/upload-artifact@v4
        with:
          name: PojavZenithHorizon(Release)
          path: app_pojav_zh/build/outputs/apk/release/*

      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: PojavZenithHorizon(Debug)
          path: app_pojav_zh/build/outputs/apk/debug/*

  build-noruntime:
    runs-on: ubuntu-latest
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}

    steps:
      - name: Set IS_MAIN_BRANCH if on main branch
        if: github.ref_name == 'main'
        run: echo "IS_MAIN_BRANCH=true" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get LWJGL3
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: main.yml
          path: app_pojav_zh/src/main/assets/components/lwjgl3
          workflow_conclusion: success
          repo: Vera-Firefly/lwjgl3-build
          branch: main
          name: lwjgl

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Debug-noruntime.apk
        run: |
          # Build the launcher
          gradle :app_pojav_zh:assembleDebug

      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: PojavZenithHorizon(Debug - No Runtime)
          path: app_pojav_zh/build/outputs/apk/debug/*
